CREATE TABLE User
(
  ID INT NOT NULL,
  Login VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Personal_account
(
  ID INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Sum INT NOT NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE Operation
(
  ID INT NOT NULL,
  Article VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Personal_Area
(
  ID INT NOT NULL,
  User_ID INT NOT NULL,
  Personal_account_ID INT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID),
  FOREIGN KEY (Personal_account_ID) REFERENCES Personal_account(ID)
);

CREATE TABLE History
(
  ID INT NOT NULL,
  Data_Time VARCHAR(255) NOT NULL,
  Sum INT NOT NULL,
  Operation_ID INT NOT NULL,
  Personal_Area_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (Operation_ID) REFERENCES Operation(ID),
  FOREIGN KEY (Personal_Area_ID) REFERENCES Personal_Area(ID)
);